<template lang="pug">
a-button(
  type="button"
  aType="default"
  text="typescript"
  if-hover="hover:bg-pink-600"
  if-focus="focus:ring-red-500"
  u-m="2"
  :loading="true"
  px="px-4"
)
a-button(
  type="button"
  aType="primary"
  text="typescript"
  if-hover="hover:bg-pink-600"
  if-focus="focus:ring-red-500"
  u-m="2"
  :loading="true"
  px="px-4"
)
</template>
